#!/bin/sh

set -e
RESULT=0

# Fail if we're not using php71+
if ! (php --version | grep -q "PHP 7.") ; then
    echo "You're not using PHP 7.1+, please install it."
    php --version
    exit 1
fi

# setup and run composer
if [ -n "$OAUTH" ]; then
    composer config -g github-oauth.github.com $OAUTH
fi

composer --no-ansi --no-interaction install

# Run PHPUnit
vendor/bin/phpunit || RESULT=1

# Run PHPCS
vendor/bin/phpcs || RESULT=1

# Run PHPStan
vendor/bin/phpstan analyse -c phpstan.neon src tests --level=7 --memory-limit=256M || RESULT=1

exit $RESULT
