#!/bin/sh

set -e
RESULT=0

# If we're not already using php70+, try and solve that
if ! (php --version | grep -q "PHP 7") ; then
    echo "You're not using PHP 7, please install it."
    php --version
    exit 1
fi

export SYMFONY_ENV=prod;

# Download and run composer
if [ ! -f "composer.phar" ]; then
    curl -sS https://getcomposer.org/installer | php
fi
if [ -n "$OAUTH" ]; then
    php composer.phar config -g github-oauth.github.com $OAUTH
fi
# Make sure the reports directory exists
if [ ! -d "build/reports" ]; then
    mkdir -p build/reports
fi

php composer.phar --no-ansi --no-interaction install

# Show php version for debugging
php --version

# Run PHPUnit
vendor/bin/phpunit || RESULT=1

# Run PHPCS
vendor/bin/phpcs --report=checkstyle --report-file=build/reports/checkstyle.xml || RESULT=1

if [ "$RESULT" = "0" ]; then
    php composer.phar --no-ansi --no-interaction --no-dev --optimize-autoloader --prefer-dist install || RESULT=1
fi

exit $RESULT
