#!/bin/sh

function docker_run {
    docker run --rm \
    -u `id -u`:`id -g` \
    -e OAUTH="$OAUTH_TOKEN" \
    -v "$WORKSPACE":/mnt/ \
    -v /etc/pki/tls/private/client.key:/etc/pki/tls/private/client.key \
    -v /etc/pki/tls/certs/client.crt:/etc/pki/tls/certs/client.crt \
    -v /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt \
    registry.ci.rmp.api.bbci.co.uk/programmes-docker-centos7 "$@"
}

set -e

branch=$(echo $GIT_BRANCH | cut -d/ -f 2)
echo $JOB_NAME:$branch $WORKSPACE

# clear old build files and tmp folder
rm -rf RPMS SOURCES SPECS SRPMS tmp

echo "Pulling latest Docker image version"
docker pull registry.ci.rmp.api.bbci.co.uk/programmes-docker-centos7:latest

echo "Running CI in container..."
docker_run script/ci-docker
